name: 'webext-buildtools-chrome-webstore-upload-action'
description: 'Upload your WebExtension to Chrome Web Store'
author: 'cardinalby'
inputs:
  zipFilePath:
    description: 'Path to WebExtension directory'
    required: true
  extensionId:
    description: 'Your extension id in Chrome Web Store'
    required: true
  apiAccessToken:
    description: 'Google API access token obtained by yourself'
    required: false
  apiClientId:
    description: 'Web Store API Client Id (use secrets!) required to obtain access token'
    required: false
  apiClientSecret:
    description: 'Web Store API Client Secret (use secrets!) required to obtain access token'
    required: false
  apiRefreshToken:
    description: 'Web Store API Refresh token (use secrets!) required to obtain access token'
    required: false
  errorIfAlreadyUploaded:
    description: 'Finish with error if the same version is already uploaded'
    required: false
    default: 'true'
  waitForUploadCheckCount:
    description: 'Checks count in case of upload finished with IN_PROGRESS status'
    required: false
  waitForUploadCheckIntervalMs:
    description: 'Checks interval in ms in case of upload finished with IN_PROGRESS status'
    required: false
outputs:
  oldVersion:
    description: 'Version of extension before uploading'
  newVersion:
    description: 'Version of extension after uploading (if was uploaded)'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
